### ISSUE TITLE
error invalid hexify value in project 2 after yarn ts-node --files .\scripts\deploy.ts Proposal_1 Proposal_2 Proposal_3

### ISSUE THREAD

**Issue by kasmaldev** [Encode-Club-Solidity-Group-14/project_week_02#1]
Project 1 works fine in code review William great work.. fantastic

However in project 2. I'm getting error invalid hexify value ...please see screenshot zoom in. Your code is excellent excellent but cannot use any of the commands in command prompt. I must be doing something wrong in my code review of your project 2 as project 1 works fine in y environment.. do I need to connect my fresh wallet to project 2 script files ?

error invalid hexify value in project 2 after yarn ts-node --files .\scripts\deploy.ts Proposal_1 Proposal_2 Proposal_3 and remaining ts-node commands
![20220708_151350](https://user-images.githubusercontent.com/101724470/178036625-b48779ec-27f5-4643-b1ac-9df207071022.jpg)
![20220708_145207](https://user-images.githubusercontent.com/101724470/178036704-cd5f8ec9-0232-47b5-a71e-35441dc4111d.jpg)

**Comment by kasmaldev** [comment]
have the remaining 4 team members  tried cloning project 1 and project 2 from our team github page and running code on their local machines  # ?

**Comment by wgcisotto** [comment]
Hi! @kasmaldev 

Thank you again! 

By the error, I see that is missing to set up the .env with our private keys, for this weekend project we have used 3 different private keys on this file. 

If you have the file make sure to include all these entries:

```
PRIVATE_KEY="YOUR_PK_1"
PRIVATE_KEY_2="YOUR_PK_2"
PRIVATE_KEY_3="YOUR_PK_3"
```

**Comment by kasmaldev** [comment]
William pointed out how to fix my ene.example file . so problem fixed and contracts deployed 
Thank you william for the guidance and assistance and by developing bug free code. marks 10 out of 10.

$ "C:\kas tests\2\project_week_02-main\node_modules\.bin\ts-node" --files .\scripts\deploy.ts Proposal_1 Proposal_2 Proposal_3
Using address 0x56D21d44F1C4c1ae0a5FF5d589CC344292A1E9c2
========= NOTICE =========
Request-Rate Exceeded  (this message will not be repeated)

The default API keys for each service are provided as a highly-throttled,
community resource for low-traffic projects and early prototyping.

While your application will continue to function, we highly recommended
signing up for your own API keys to improve performance, increase your
request rate/limit and enable other perks, such as metrics and advanced APIs.

For more details: https://docs.ethers.io/api-keys/
==========================
Wallet balance 44.984589127985174
Wallet balance 44.984589127985174
Deploying Ballot contract
Proposals:
Proposal N. 1: Proposal_1
Proposal N. 2: Proposal_2
Proposal N. 3: Proposal_3
Awaiting confirmations
Awaiting confirmations
Completed
Token Contract deployed at 0x788C6A434C322C51DcE451698A0dd4457873e62D
Custom Ballot Contract deployed at 0x5935bb3a43dC57072F3BfB1B7BbA87df64C8420d
Done in 74.99s.
