### ISSUE TITLE
Creation of Menu Options to Run Scripts

### ISSUE THREAD

**Issue by wgcisotto** [Encode-Club-Solidity-Group-14/project_week_02#3]
### Menu to execute scripts

In order to facilitate the execution of all scripts, I propose the creation of a single script with a menu option that executes all other scripts. 

Example of the menu:
- Deploy 
- Query Proposal by index
- Mint
- Delegate Vote 
- Cast Vote 
- Query Results
- Create Ballot from snapshots

**Comment by kasmaldev** [comment]
Yes I agree to your proposal . You mentioned Lottery lecture way to run scripts from single file. Please guide us the remaining group members. Thank you

**Comment by kasmaldev** [comment]
solved by william
